version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Vue1578!
      MYSQL_DATABASE: teal_todo
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env.production
    depends_on:
      - db
    command: npm run start:prod  # ✅ これを追加！

  frontend:
    build: ./frontend/todo2
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data:
